# Generated by Django 5.2.16 on 2026-07-19 14:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nome')),
                ('slug', models.SlugField(unique=True, verbose_name='identificador')),
                ('default_freight', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='frete padrão (R$/un)')),
            ],
            options={
                'verbose_name': 'canal',
                'verbose_name_plural': 'canais',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='equipamento')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='categoria')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='data de aquisição')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='valor pago (R$)')),
                ('useful_life_months', models.PositiveIntegerField(blank=True, null=True, verbose_name='vida útil (meses)')),
                ('maintenance_status', models.CharField(blank=True, default='Em dia', max_length=50, verbose_name='status manutenção')),
            ],
            options={
                'verbose_name': 'equipamento',
                'verbose_name_plural': 'equipamentos',
            },
        ),
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='custo por hora (R$)')),
            ],
            options={
                'verbose_name': 'artesã',
                'verbose_name_plural': 'artesãs',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('category', models.CharField(choices=[('gifts', 'Presentes'), ('stationery', 'Papelaria'), ('memories', 'Memórias'), ('school', 'Escolar'), ('other', 'Outros')], default='other', max_length=20, verbose_name='categoria')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('is_combo', models.BooleanField(default=False, verbose_name='é kit')),
                ('material_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=9, verbose_name='custo de material (R$)')),
                ('packaging_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=9, verbose_name='custo de embalagem (R$)')),
                ('waste_pct', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='perda sobre material (fração)')),
                ('production_time_min', models.PositiveIntegerField(default=0, verbose_name='tempo de produção (min/lote)')),
                ('batch_size', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='tamanho do lote')),
                ('target_margin_pct', models.DecimalField(decimal_places=4, default=Decimal('0.5'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('0.99'))], verbose_name='margem-alvo (fração)')),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='preço base (R$)')),
                ('maker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.maker', verbose_name='artesã')),
            ],
            options={
                'verbose_name': 'produto',
                'verbose_name_plural': 'produtos',
            },
        ),
        migrations.CreateModel(
            name='ComboItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantidade')),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_items', to='core.product', verbose_name='kit')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_combos', to='core.product', verbose_name='componente')),
            ],
            options={
                'verbose_name': 'componente do kit',
                'verbose_name_plural': 'componentes do kit',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='data')),
                ('customer_name', models.CharField(blank=True, max_length=120, verbose_name='cliente')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('completed', 'Concluída'), ('canceled', 'Cancelada')], default='completed', max_length=10, verbose_name='situação')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.channel', verbose_name='canal')),
            ],
            options={
                'verbose_name': 'venda',
                'verbose_name_plural': 'vendas',
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantidade')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='preço unitário (R$)')),
                ('unit_cogs', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=9, verbose_name='custo unitário (R$)')),
                ('unit_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=9, verbose_name='taxa unitária (R$)')),
                ('unit_freight', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='frete unitário (R$)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product', verbose_name='produto')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.sale', verbose_name='venda')),
            ],
            options={
                'verbose_name': 'item da venda',
                'verbose_name_plural': 'itens da venda',
            },
        ),
        migrations.CreateModel(
            name='ChannelFeeTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='preço a partir de (R$)')),
                ('commission_pct', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='comissão (fração)')),
                ('fixed_fee', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='taxa fixa (R$)')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_tiers', to='core.channel', verbose_name='canal')),
            ],
            options={
                'verbose_name': 'faixa de taxa',
                'verbose_name_plural': 'faixas de taxa',
                'ordering': ['channel', 'min_price'],
                'constraints': [models.UniqueConstraint(fields=('channel', 'min_price'), name='unique_tier_per_channel_price')],
            },
        ),
    ]
