# Generated by Django 5.2.16 on 2026-07-20 01:00

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelfeetier',
            name='commission_pct',
            field=models.DecimalField(decimal_places=4, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='comissão (fração)'),
        ),
        migrations.AlterField(
            model_name='channelfeetier',
            name='fixed_fee',
            field=models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='taxa fixa (R$)'),
        ),
        migrations.AlterField(
            model_name='channelfeetier',
            name='min_price',
            field=models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='preço a partir de (R$)'),
        ),
    ]
