# Generated by Django 5.2.16 on 2026-07-27 13:24

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_channelfeetier_commission_pct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='waste_pct',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='perda sobre material (fração)'),
        ),
    ]
