# Generated by Django 5.2.16 on 2026-08-15 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_order_total_sales'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saleitem',
            options={'ordering': ['id'], 'verbose_name': 'item da venda', 'verbose_name_plural': 'itens da venda'},
        ),
    ]
